### ISSUE TITLE
route:list vendor:publish等命令用不了

### ISSUE THREAD

**Issue by skys215** [toplan/laravel-sms#139]
Laravel5.4, ElCapitan
日志如下
```
[2017-03-27] local.ERROR: ErrorException: Illegal offset type in unset in vendor/laravel/framework/src/Illuminate/Container/Container.php:1057
Stack trace:
#0 vendor/laravel/framework/src/Illuminate/Container/Container.php(1057): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Illegal offset ...', '/Library/WebSer...', 1057, Array)
#1 vendor/laravel/framework/src/Illuminate/Container/Container.php(211): Illuminate\Container\Container->dropStaleInstances(Array)
#2 vendor/laravel/framework/src/Illuminate/Container/Container.php(322): Illuminate\Container\Container->bind(Array, Object(Closure), true)
#3 vendor/toplan/phpsms/src/phpsms/PhpSmsServiceProvider.php(51): Illuminate\Container\Container->singleton(Array, Object(Closure))
#4 vendor/laravel/framework/src/Illuminate/Foundation/Application.php(568): Toplan\PhpSms\PhpSmsServiceProvider->register()
#5 vendor/laravel/framework/src/Illuminate/Foundation/Application.php(677): Illuminate\Foundation\Application->register(Object(Toplan\PhpSms\PhpSmsServiceProvider))
#6 vendor/laravel/framework/src/Illuminate/Foundation/Application.php(657): Illuminate\Foundation\Application->registerDeferredProvider('Toplan\\PhpSms\\P...', 'phpsms.sms')
#7 vendor/laravel/framework/src/Illuminate/Foundation/Application.php(633): Illuminate\Foundation\Application->loadDeferredProvider('phpsms.sms')
#8 vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(276): Illuminate\Foundation\Application->loadDeferredProviders()
#9 vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(115): Illuminate\Foundation\Console\Kernel->bootstrap()
#10 artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 {main}  
```

**Comment by toplan** [comment]
见 #140
